up: 
	scp -r /Users/NAVhjelpemiddelsentrals/Dropbox/Skole/TDT4200/PS5/kmeans jorgenfa@gpu04.idi.ntnu.no:

down: 
	scp -r jorgenfa@gpu04.idi.ntnu.no:/home/jorgenfa/PS5/kmeans /Users/NAVhjelpemiddelsentrals/Dropbox/Skole/TDT4200/PS5
